apiVersion: apps/v1

kind: Deployment
metadata:
  name: go-web-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-app
  template:
    metadata:
      labels:
        app: go-web-app
    spec:
      containers:
      - name: go-web-app
        image: pattabi95/go-web-app:v1
        ports:
        - containerPort: 8080
